version: "3.8"

services:
  mongo:
    image: mongo:${MONGO_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-unifi}_mongo
    networks:
      - unifi
    restart: unless-stopped
    volumes:
      - unifi-db-data:/data/db
      - unifi-db-config:/data/configdb

  controller:
    image: jacobalberty/unifi:${UNIFI_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME:-unifi}_controller
    depends_on:
      - mongo
    init: true  # Ensures proper handling of PID 1 processes
    networks:
      - unifi
    restart: unless-stopped
    volumes:
      - unifi-data:/unifi
    user: unifi
    environment:
      DB_URI: "mongodb://mongo/unifi"
      STATDB_URI: "mongodb://mongo/unifi_stat"
      DB_NAME: "unifi"
      UNIFI_HTTP_PORT: "${UNIFI_HTTP_PORT:-8880}"
      UNIFI_HTTPS_PORT: "${UNIFI_HTTPS_PORT:-8843}"
      TZ: "${TZ:-UTC}"
    ports:
      - "3478:3478/udp"    # STUN service
      - "5514:5514/udp"    # Remote syslog capture
      - "6789:6789/tcp"    # UniFi mobile speed test
      - "8080:8080/tcp"    # Device & application communication
      - "8880:8880/tcp"    # HTTP service
      - "8843:8843/tcp"    # HTTPS service
      - "10001:10001/udp"  # Device discovery
      - "${UNIFI_HTTP_PORT:-8880}:${UNIFI_HTTP_PORT:-8880}/tcp"
      - "${UNIFI_HTTPS_PORT:-8843}:${UNIFI_HTTPS_PORT:-8843}/tcp"

volumes:
  unifi-db-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${UNIFI_DB_DATA_VOLUME_PATH}"

  unifi-db-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${UNIFI_DB_CONFIG_VOLUME_PATH}"

  unifi-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${UNIFI_VOLUME_PATH}"

networks:
  unifi:
    driver: bridge
